# Generated by Django 4.2.27 on 2026-01-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_description_alter_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='expected_salary',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='preferred_technology',
            field=models.CharField(max_length=100),
        ),
    ]
