# Generated by Django 4.2.27 on 2026-01-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
