# Generated by Django 6.0 on 2026-01-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('keywords', models.TextField(help_text='comma separated keywords: react, django, remote, fresher')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=50)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=30)),
                ('experience_min', models.IntegerField(default=0)),
                ('experience_max', models.IntegerField(default=0)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('priority_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_search_index',
                'indexes': [models.Index(fields=['job_id'], name='job_search__job_id_6ccd3d_idx'), models.Index(fields=['title'], name='job_search__title_ee4ce5_idx'), models.Index(fields=['company'], name='job_search__company_782342_idx'), models.Index(fields=['city'], name='job_search__city_97c236_idx'), models.Index(fields=['work_mode'], name='job_search__work_mo_1b3318_idx'), models.Index(fields=['job_type'], name='job_search__job_typ_599f35_idx'), models.Index(fields=['experience_min'], name='job_search__experie_e1e115_idx'), models.Index(fields=['salary_min'], name='job_search__salary__96f424_idx')],
            },
        ),
    ]
